### ISSUE TITLE
Linking with all compression libs at once: -lz  -lcurl -lm -lpthread -ldeflate -llzma -lbz2  -ldeflate

### ISSUE THREAD

**Issue by mmokrejs** [jkbonfield/io_lib#13]
Hi James,
  provided the new and preferred dependency in io_lib-1.14.11 is libdeflate, would you please comment on the below link line? Is it correct that all the zlib/bz2/lzma/libdeflate libs are provided on the link line? Shouldn't configure pick only the preferred-ones (say libdeflate and never ever include zlib for example)? I have no idea if say bzip2 and lzma are used for same functionalities or not, hence asking. Maybe update the Readme.md as well? Thank you.

```
/bin/sh ../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc  -Wall -O2 -pipe -mpclmul -mpopcnt -march=native -ftree-vectorize -version-info 13:1:0  -Wl,-O1 -Wl,--as-needed -o libstaden-read.la -rpath /usr/lib64 libstaden_read_la-Read.lo libstaden_read_la-scf_extras.lo libstaden_read_la-translate.lo libstaden_read_la-compression.lo libstaden_read_la-ztr.lo libstaden_read_la-ztr_translate.lo libstaden_read_la-deflate_interlaced.lo libstaden_read_la-fpoint.lo libstaden_read_la-seqIOABI.lo libstaden_read_la-seqIOALF.lo libstaden_read_la-expFileIO.lo libstaden_read_la-seqIOPlain.lo libstaden_read_la-misc_scf.lo libstaden_read_la-read_scf.lo libstaden_read_la-write_scf.lo libstaden_read_la-sff.lo libstaden_read_la-srf.lo libstaden_read_la-array.lo libstaden_read_la-compress.lo libstaden_read_la-error.lo libstaden_read_la-files.lo libstaden_read_la-find.lo libstaden_read_la-mach-io.lo libstaden_read_la-open_trace_file.lo libstaden_read_la-read_alloc.lo libstaden_read_la-strings.lo libstaden_read_la-traceType.lo libstaden_read_la-xalloc.lo libstaden_read_la-vlen.lo libstaden_read_la-hash_table.lo libstaden_read_la-jenkins_lookup3.lo libstaden_read_la-mFILE.lo libstaden_read_la-pooled_alloc.lo libstaden_read_la-bam.lo libstaden_read_la-sam_header.lo libstaden_read_la-rANS_static.lo libstaden_read_la-rANS_static4x16pr.lo libstaden_read_la-cram_codecs.lo libstaden_read_la-cram_encode.lo libstaden_read_la-cram_decode.lo libstaden_read_la-cram_stats.lo libstaden_read_la-cram_io.lo libstaden_read_la-cram_index.lo libstaden_read_la-zfio.lo libstaden_read_la-dstring.lo libstaden_read_la-string_alloc.lo libstaden_read_la-md5.lo libstaden_read_la-crc32.lo libstaden_read_la-scram.lo libstaden_read_la-thread_pool.lo libstaden_read_la-binning.lo libstaden_read_la-cram_bambam.lo libstaden_read_la-bgzip.lo libstaden_read_la-tokenise_name3.lo libstaden_read_la-fqzcomp_qual.lo -lz  -lcurl -lm -lpthread -ldeflate -llzma -lbz2  -ldeflate
```

**Comment by jkbonfield** [comment]
On Tue, Jan 22, 2019 at 03:42:08AM -0800, Martin Mokrej? wrote:
>   provided the new and preferred dependency in io_lib-1.14.11 is libdeflate, would you please comment on the below link line? Is it correct that all the zlib/bz2/lzma/libdeflate libs are provided on the link line? Shouldn't configure pick only the preferred-ones (say libdeflate and never ever include zlib for example)? I have no idea if say bzip2 and lzma are used for same functionalities or not, hence asking. Maybe update the Readme.md as well? Thank you.

Libdeflate doesn't cover everything that zlib can do.  Specifically
libdeflate is non-streaming, so it is given a buffer and returns a
buffer.  This is normally what we want most, but it's not the sole
capability we use.

The API differs too, so supplying both isn't a problem anyway as the
code won't get confused as to which one it is calling.  (That needs to
be done via #ifdefs in the code.)

Bzip2 and lzma are completely different algorithms.  They are included
because CRAM files *may* use them.  By default we don't use them
because IMO they don't offer great savings for the additional CPU
cost.  (Bzip2 may be woth it in some cases, but lzma is too costly for
most users.)

James
-- 
James Bonfield (jkb@sanger.ac.uk)
The Sanger Institute, Hinxton, Cambs, CB10 1SA


-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by mmokrejs** [comment]
Thank you James, excellent explanation, so nothing to worry about.
