### ISSUE TITLE
Handling of long (>65k) CIGAR strings

### ISSUE THREAD

**Issue by rob-p** [jkbonfield/io_lib#28]
Hi @jkbonfield,

  I was just wondering where libstaden is regarding support for long CIGAR strings (those with >65k operations).  Specifically, I realize there was some official consensus a while ago about how this is [handled in htslib and samtools](https://github.com/samtools/hts-specs/issues/40).  Is this handled in io_lib?  If so, how?  If not, are there plans to do it?  I realize it may not be a priority, and I was just curious because I'd like to know if it makes sense to start transitioning some code (that needs to deal with long reads) over to samtools.  Originally, I opted for libstaden (and it has been _fantastic_) because it supported multithreaded decompression when samtools did not.  However, now both libraries do.  Obviously, I'd prefer to stick with the current library to avoid unnecessary code changes, but the feasibility of that depends on long-read support.

Thanks!
Rob

**Comment by jkbonfield** [comment]
Hello,

Io_lib does deal with long CIGARs and did so for a considerable time before htslib (proposed 4 years before, implemented in code 3 years before due to necessity as part of Gap5).  Io_lib uses the bin field to get extra bits for storing CIGAR size and an additional FLAG to indicate this.  It was considered for htslib too, but ultimately rejected in favour of using a new CG auxliary tag instead.

Thus sadly, io_lib and htslib are incompatible in this regard!  I had forgotten about this actually and should fix it so it can read and write the official spec way of doing this.

I should point out though that switching to htslib is probably wise still.  Over the years we've managed to copy over most of what made io_lib distinctive, including the thread pool and highly optimised SAM parser, and htslib is now superior in some cases (such as multi-threaded SAM decoding, which is absent in io_lib).  Additionally htslib is obviously is more feature rich, with various remote file protocols, while even some basic things like BAI indices are absent in io_lib.  Htslib will be better tested too, and therefore quite probably has fewer bugs.

Meanwhile, I'll have a look at how hard it is to get io_lib to cope with both variants of long cigars.

**Comment by jkbonfield** [comment]
I've made a PR and manually tested it (it's quite a large chunk of extra test data so it's not ideal to incorporate to the automated suite).  It handles both the original io_lib way of doing things as well as the official hts-specs BAM (which it now uses when writing).

I'd appreciate if you can validate that PR #29 solves this issue for you.
