### ISSUE TITLE
configure and bzip2 library

### ISSUE THREAD

**Issue by gt1** [jkbonfield/io_lib#30]
Hello James,

the io_lib configure script checks for the presence of BZ2_bzBuffToBuffCompress, but uses

```
#include <bzlib.h>
```

even if it is not present (for instance in htscodecs/htscodecs/arith_dynamic.c). Maybe the configure run should just fail, if the bzip2 support library and headers are not available.

Best,
German

**Comment by jkbonfield** [comment]
This is an htscodecs bug rather than io_lib, but I'm working on it now.  I'm not entirely convinced the bzip2 usage there adds anything at all frankly and it probably should be culled.  In light of that I'll put in ifdefs and make sure it's optional.

I'd like to also improve the configure output to have a summary at the end, like I did with the Staden Package many years back.  No one reads through the wall of text to see what did and didn't get included.  The alternative is, given CRAM supports bzip2 and lzma, to make them configure failures with options to explicitly disable.  That's the approach we use in htslib, so you can't accidentally sleep-walk into compiling with components missing and it has to be an explicit request.
