### ISSUE TITLE
cram_index producing bad indexes

### ISSUE THREAD

**Issue by sb10** [jkbonfield/io_lib#6]
Using version 1.14.9 and this cram file: s3://sb10_syndip_tests/out/syndip.mf.t4.5x.bwa.alts.samtools.sup.withoutJKB.withoutBAQ.cram

`cram_index` produces a .crai file that looks like:

```
gunzip -c syndip.mf.t4.5x.bwa.alts.samtools.sup.withoutJKB.withoutBAQ.cram.crai | head -n 22568 | tail -n 3
455	10637	159361	16103633679	535	1153110
456	1	-2147483648	16103633679	535	1153110
457	1	3033	16103633679	535	1153110
```

`samtools index`, on the other hand, produces:

```
455	10637	159361	16103633679	535	1153110
456	1	53	16103633679	535	1153110
457	1	3033	16103633679	535	1153110
```

**Comment by jkbonfield** [comment]
This appears to be the same bug fixed in htslib https://github.com/samtools/htslib/commit/a58cd8547526a3be537064639572ff767298326d some time ago and also fixed here as 1153f052d4ab228160174e0bc2e012951a5da2c0.

Htslib has had a release since then, but not io_lib.  I wasn't aware it had been so long since I did a release here.

A new one will be coming soon I hope.

**Comment by sb10** [comment]
Thanks. Do you announce releases anywhere? We'll need to add the fixed one to our conda channel. Can you let me know?

**Comment by jkbonfield** [comment]
Nowhere other than here, but I'll let you know when it's done.
